import {
  BranchTenant,
  ServiceConfig,
  DepartmentConfig,
  Child,
  AttendanceRecord,
  ChurchSettings,
} from './types';

export const DEFAULT_BRANCHES: BranchTenant[] = [
  {
    id: 'branch-uyo',
    name: 'Uyo Parish',
    shortName: 'Uyo',
    churchName: 'The Covenant Nation Uyo',
    city: 'Uyo',
    state: 'Akwa Ibom State',
    branchVenue: 'Vinpy Events Centre, 10 Udo Udoma Avenue, Uyo, Akwa Ibom State',
    contactEmail: 'tcnuyo@gmail.com',
    emergencyPhone: '+234 803 762 9110',
    pastorInCharge: 'Pastor In Charge - TCN Uyo',
    childrenPastor: 'Children & Teens Ministry Coordinator',
    adminPasscode: '1234',
    schedules: [
      { label: '1st Service', time: '8:00 AM' },
      { label: '2nd Service', time: '10:30 AM' },
      { label: 'Single / Special', time: '8:30 AM' },
    ],
    instagramUrl: 'https://instagram.com',
    facebookUrl: 'https://facebook.com',
    isActive: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'branch-iganmu',
    name: 'Iganmu Center (Main)',
    shortName: 'Iganmu',
    churchName: 'The Covenant Nation Iganmu',
    city: 'Lagos Mainland',
    state: 'Lagos State',
    branchVenue: 'The Covenant Centre, National Theatre Complex, Iganmu, Lagos',
    contactEmail: 'tcniganmu@gmail.com',
    emergencyPhone: '+234 802 300 0001',
    pastorInCharge: 'Pastor Poju Oyemade',
    childrenPastor: 'Pastor Toyin Poju-Oyemade',
    adminPasscode: '1234',
    schedules: [
      { label: '1st Service', time: '7:00 AM' },
      { label: '2nd Service', time: '9:00 AM' },
      { label: '3rd Service', time: '11:00 AM' },
    ],
    instagramUrl: 'https://instagram.com/covenantnation',
    facebookUrl: 'https://facebook.com/covenantnation',
    isActive: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'branch-lekki',
    name: 'Lekki Parish (The Covenant Place)',
    shortName: 'Lekki',
    churchName: 'The Covenant Nation Lekki',
    city: 'Lekki',
    state: 'Lagos State',
    branchVenue: 'The Covenant Place, Opposite Alpha Beach, Lekki Expressway, Lagos',
    contactEmail: 'tcnlekki@gmail.com',
    emergencyPhone: '+234 803 400 0002',
    pastorInCharge: 'Resident Pastor - TCN Lekki',
    childrenPastor: 'Lekki Children Ministry Lead',
    adminPasscode: '1234',
    schedules: [
      { label: '1st Service', time: '7:30 AM' },
      { label: '2nd Service', time: '9:30 AM' },
      { label: '3rd Service', time: '11:30 AM' },
    ],
    instagramUrl: 'https://instagram.com',
    facebookUrl: 'https://facebook.com',
    isActive: true,
    createdAt: '2024-02-15',
  },
  {
    id: 'branch-abuja',
    name: 'Abuja Central',
    shortName: 'Abuja',
    churchName: 'The Covenant Nation Abuja',
    city: 'Abuja',
    state: 'FCT',
    branchVenue: 'International Conference Centre, Central Area, Abuja, FCT',
    contactEmail: 'tcnabuja@gmail.com',
    emergencyPhone: '+234 809 500 0003',
    pastorInCharge: 'Resident Pastor - TCN Abuja',
    childrenPastor: 'Abuja Children Ministry Lead',
    adminPasscode: '1234',
    schedules: [
      { label: '1st Service', time: '8:00 AM' },
      { label: '2nd Service', time: '10:15 AM' },
    ],
    instagramUrl: 'https://instagram.com',
    facebookUrl: 'https://facebook.com',
    isActive: true,
    createdAt: '2024-03-20',
  },
];

export const DEFAULT_SERVICES: ServiceConfig[] = [
  {
    id: 'first-service',
    name: 'First Service',
    time: '08:00 AM - 09:30 AM',
    day: 'Sunday',
    isActive: true,
    description: 'Early Sunday Morning Worship & Children Church Class',
  },
  {
    id: 'second-service',
    name: 'Second Service',
    time: '10:30 AM - 12:15 PM',
    day: 'Sunday',
    isActive: true,
    description: 'Main Sunday Celebration & Interactive Bible Teaching',
  },
  {
    id: 'mid-week-service',
    name: 'Mid-Week Service',
    time: '06:00 PM - 07:45 PM',
    day: 'Wednesday',
    isActive: true,
    description: 'Wednesday Word, Faith Clinic & Children Discovery Hour',
  },
  {
    id: 'others-special',
    name: 'Special Service / Others',
    time: '08:30 AM - 10:30 AM',
    day: 'All',
    isActive: true,
    description: 'Single, Thanksgiving, Youth Camps, Easter, Christmas Fest',
  },
];

export const DEFAULT_DEPARTMENTS: DepartmentConfig[] = [
  {
    id: 'dept-little-angels',
    name: 'Little Angels (Creche / Toddlers)',
    ageRange: '0 - 3 Years',
    minAge: 0,
    maxAge: 3,
    location: 'Ground Floor Room 1 (Nursery Wing)',
    color: 'amber',
    teacherInCharge: 'Teacher Faith Bassey',
    notes: 'Diaper changing station, nap cots, nursing mothers comfort room',
  },
  {
    id: 'dept-stars',
    name: 'Stars & Sunbeams',
    ageRange: '4 - 5 Years',
    minAge: 4,
    maxAge: 5,
    location: 'Ground Floor Hall A',
    color: 'emerald',
    teacherInCharge: 'Teacher Blessing Okon',
    notes: 'Bible storytelling, color activities, action songs and snacks',
  },
  {
    id: 'dept-kingdom-kids',
    name: 'Kingdom Kids',
    ageRange: '6 - 8 Years',
    minAge: 6,
    maxAge: 8,
    location: 'Hall B (First Floor)',
    color: 'sky',
    teacherInCharge: 'Teacher Emmanuel Udoh',
    notes: 'Memory verses, scriptural drama, quizzes and interactive learning',
  },
  {
    id: 'dept-junior',
    name: 'Junior Church',
    ageRange: '9 - 12 Years',
    minAge: 9,
    maxAge: 12,
    location: 'Youth Annex Hall 2',
    color: 'indigo',
    teacherInCharge: 'Teacher Anietie Ekong',
    notes: 'Foundational doctrines, leadership training, prayer groups',
  },
  {
    id: 'dept-teens',
    name: 'Teens / Pacesetters',
    ageRange: '13 - 17 Years',
    minAge: 13,
    maxAge: 17,
    location: 'Upper Gallery / Teens Sanctuary',
    color: 'rose',
    teacherInCharge: 'Pastor Daniel Archibong',
    notes: 'Contemporary worship, career guidance, discipleship and fellowship',
  },
];

export const getTodayDateString = (): string => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const RAW_SAMPLE_CSV_TEXT = `Full Name,Age,Class,Gender,Parent Name,Phone,Alt Phone,Email,Address,Emergency Contact,Allergies,Special Notes
"David John","8","Kingdom Kids","Boy","Mrs John","08034567890","08098765432","mrs.john@familymail.com","14 Grace Avenue, Sunrise Estate","Mr David John Sr (08098765432)","None","First time visitor"
"Sarah Oluwaseun","3","Little Angels","Girl","Deacon & Mrs Oluwaseun","08023456781","","oluwaseun@family.org","7 Grace Close, Phase 2","Elder Mark (08033441122)","No dairy products","Loves singing"
"Daniel Okon","5","Stars & Sunbeams","Boy","Pastor Okon","08076543210","08011223344","okon.p@sanctuary.org","22 Faith Estate, Ring Road","Sister Mary (08023456701)","Asthma inhaler in bag","Allergic to dust"
"Hannah Adeleke","11","Junior Church","Girl","Bro Emmanuel Adeleke","08055667788","","adeleke.fam@yahoo.com","5 Glory Street, Eden Gardens","Uncle Paul (08066778899)","None","Junior Choir member"
"Victor Chukwudi","15","Teens / Pacesetters","Boy","Elder Chukwudi","08066778899","08033445566","chukwudi.e@telecom.ng","19 Zion Valley, Peace Hill","Deaconess Ngozi (08099887711)","None","Teens media team volunteer"
"Miracle Eze","7","Kingdom Kids","Girl","Mrs Eze","08044332211","","eze.m@gmail.com","3 Bethel Lane, Victoria Court","Auntie Joy (08055443322)","None","Plays violin"
"Samuel Bamidele","4","Stars & Sunbeams","Boy","Mrs Bamidele","08098765432","","bamidele.s@outlook.com","8 Hope Crescent, Olive Park","Mr Kunle (08022114433)","Peanut allergy","Provide fruit snack"
"Joy Nnamdi","2","Little Angels","Girl","Mrs Nnamdi","08087654321","","joy.nnamdi@gmail.com","12 Peace Garden, Palm Grove","Uncle Chidi (08077665511)","None","Crèche room 1"`;

export const SEED_CHILDREN: Child[] = [
  {
    id: 'child-01',
    branchId: 'branch-uyo',
    fullName: 'David John',
    dateOfBirth: '2018-03-12',
    age: 8,
    gender: 'Male',
    departmentId: 'dept-kingdom-kids',
    parentName: 'Mrs John',
    parentPhone: '08034567890',
    secondaryContactPhone: '08098765432',
    email: 'mrs.john@familymail.com',
    homeAddress: '14 Grace Avenue, Sunrise Estate',
    emergencyContact: 'Mr David John Sr (08098765432)',
    allergiesMedicalNotes: 'None',
    specialNotes: 'First time visitor',
    isFirstTimer: true,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-blue-600',
  },
  {
    id: 'child-02',
    branchId: 'branch-uyo',
    fullName: 'Sarah Oluwaseun',
    dateOfBirth: '2023-05-18',
    age: 3,
    gender: 'Female',
    departmentId: 'dept-little-angels',
    parentName: 'Deacon & Mrs Oluwaseun',
    parentPhone: '08023456781',
    email: 'oluwaseun@family.org',
    homeAddress: '7 Grace Close, Phase 2',
    emergencyContact: 'Elder Mark (08033441122)',
    allergiesMedicalNotes: 'No dairy products',
    specialNotes: 'Loves singing',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-emerald-600',
  },
  {
    id: 'child-03',
    branchId: 'branch-uyo',
    fullName: 'Daniel Okon',
    dateOfBirth: '2021-08-20',
    age: 5,
    gender: 'Male',
    departmentId: 'dept-stars',
    parentName: 'Pastor Okon',
    parentPhone: '08076543210',
    secondaryContactPhone: '08011223344',
    email: 'okon.p@sanctuary.org',
    homeAddress: '22 Faith Estate, Ring Road',
    emergencyContact: 'Sister Mary (08023456701)',
    allergiesMedicalNotes: 'Asthma inhaler in bag - Allergic to dust',
    specialNotes: '',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-indigo-600',
  },
  {
    id: 'child-04',
    branchId: 'branch-uyo',
    fullName: 'Hannah Adeleke',
    dateOfBirth: '2015-11-04',
    age: 11,
    gender: 'Female',
    departmentId: 'dept-junior',
    parentName: 'Bro Emmanuel Adeleke',
    parentPhone: '08055667788',
    email: 'adeleke.fam@yahoo.com',
    homeAddress: '5 Glory Street, Eden Gardens',
    emergencyContact: 'Uncle Paul (08066778899)',
    allergiesMedicalNotes: 'None',
    specialNotes: 'Junior Choir member',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-purple-600',
  },
  {
    id: 'child-05',
    branchId: 'branch-uyo',
    fullName: 'Victor Chukwudi',
    dateOfBirth: '2011-01-15',
    age: 15,
    gender: 'Male',
    departmentId: 'dept-teens',
    parentName: 'Elder Chukwudi',
    parentPhone: '08066778899',
    secondaryContactPhone: '08033445566',
    email: 'chukwudi.e@telecom.ng',
    homeAddress: '19 Zion Valley, Peace Hill',
    emergencyContact: 'Deaconess Ngozi (08099887711)',
    allergiesMedicalNotes: 'None',
    specialNotes: 'Teens media team volunteer',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-rose-600',
  },
  {
    id: 'child-06',
    branchId: 'branch-uyo',
    fullName: 'Miracle Eze',
    dateOfBirth: '2019-07-22',
    age: 7,
    gender: 'Female',
    departmentId: 'dept-kingdom-kids',
    parentName: 'Mrs Eze',
    parentPhone: '08044332211',
    email: 'eze.m@gmail.com',
    homeAddress: '3 Bethel Lane, Victoria Court',
    emergencyContact: 'Auntie Joy (08055443322)',
    allergiesMedicalNotes: 'None',
    specialNotes: 'Plays violin',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-amber-600',
  },
  {
    id: 'child-07',
    branchId: 'branch-uyo',
    fullName: 'Samuel Bamidele',
    dateOfBirth: '2022-09-30',
    age: 4,
    gender: 'Male',
    departmentId: 'dept-stars',
    parentName: 'Mrs Bamidele',
    parentPhone: '08098765432',
    email: 'bamidele.s@outlook.com',
    homeAddress: '8 Hope Crescent, Olive Park',
    emergencyContact: 'Mr Kunle (08022114433)',
    allergiesMedicalNotes: 'Peanut allergy',
    specialNotes: 'Provide fruit snack',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-teal-600',
  },
  {
    id: 'child-08',
    branchId: 'branch-uyo',
    fullName: 'Joy Nnamdi',
    dateOfBirth: '2024-04-10',
    age: 2,
    gender: 'Female',
    departmentId: 'dept-little-angels',
    parentName: 'Mrs Nnamdi',
    parentPhone: '08087654321',
    email: 'joy.nnamdi@gmail.com',
    homeAddress: '12 Peace Garden, Palm Grove',
    emergencyContact: 'Uncle Chidi (08077665511)',
    allergiesMedicalNotes: 'None',
    specialNotes: 'Crèche room 1',
    isFirstTimer: false,
    registeredDate: getTodayDateString(),
    avatarColor: 'bg-pink-600',
  },
];

export const SEED_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    branchId: 'branch-uyo',
    childId: 'child-01',
    childName: 'David John',
    serviceId: 'first-service',
    serviceName: 'First Service',
    departmentId: 'dept-kingdom-kids',
    departmentName: 'Kingdom Kids',
    date: getTodayDateString(),
    checkInTime: '07:45 AM',
    status: 'checked_in',
    pickupSecurityCode: 'TCN-8421',
    parentName: 'Mrs John',
    parentPhone: '08034567890',
    checkedInBy: 'Usher Desk',
    allergiesMedicalNotes: 'None',
  },
  {
    id: 'att-02',
    branchId: 'branch-uyo',
    childId: 'child-02',
    childName: 'Sarah Oluwaseun',
    serviceId: 'first-service',
    serviceName: 'First Service',
    departmentId: 'dept-little-angels',
    departmentName: 'Little Angels (Creche / Toddlers)',
    date: getTodayDateString(),
    checkInTime: '07:52 AM',
    status: 'checked_in',
    pickupSecurityCode: 'TCN-3914',
    parentName: 'Deacon & Mrs Oluwaseun',
    parentPhone: '08023456781',
    checkedInBy: 'Usher Desk',
    allergiesMedicalNotes: 'No dairy products',
  },
  {
    id: 'att-03',
    branchId: 'branch-uyo',
    childId: 'child-07',
    childName: 'Samuel Bamidele',
    serviceId: 'first-service',
    serviceName: 'First Service',
    departmentId: 'dept-stars',
    departmentName: 'Stars & Sunbeams',
    date: getTodayDateString(),
    checkInTime: '07:58 AM',
    checkOutTime: '09:20 AM',
    status: 'checked_out',
    pickupSecurityCode: 'TCN-5108',
    parentName: 'Mrs Bamidele',
    parentPhone: '08098765432',
    checkedInBy: 'Teacher Blessing Okon',
    checkedOutBy: 'Mrs Bamidele',
    allergiesMedicalNotes: 'Peanut allergy',
  },
];
